modLoader="javafml"
loaderVersion="[31,)"
[[mods]] #mandatory
modId="progexpansionarmory"
version="1.16.1-0.1.0"
displayName="Progression Expansion: Armory"
authors="Nylanomel, Pylerrr"
description='''
An addon for Progression Expansion
'''
[[dependencies.progexpansionarmory]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.progexpansionarmory]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
[[dependencies.progexpansionarmory]]
    modId="progexpansion"
    mandatory=true
    versionRange="[1.0.0,)"
    ordering="NONE"
    side="BOTH"